import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms under which you can use ContentGenie.",
};

export default function TermsPage() {
  return (
    <article className="space-y-6">
      <h1 className="text-3xl font-bold tracking-tight mb-4">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-8">
        Placeholder — full terms coming before we exit beta.
      </p>
      <p className="text-[15px] leading-relaxed text-muted-foreground">
        ContentGenie is a public-beta product. The service is provided as-is;
        features may change without notice. You agree not to abuse the service
        (bulk scraping, reverse-engineering AI summaries for resale, sharing your
        account). AI summaries are generated by third-party language models and
        may contain errors — treat them as starting points, not final answers.
      </p>
      <p className="text-[15px] leading-relaxed text-muted-foreground mt-6">
        Beta accounts that join before we leave public beta are grandfathered to
        50% off whatever our launch pricing turns out to be, for as long as the
        subscription stays active.
      </p>
      <p className="text-[15px] leading-relaxed text-muted-foreground mt-6">
        Questions?{" "}
        <a
          className="underline underline-offset-4 hover:text-foreground"
          href="mailto:hello@contentgenie.app"
        >
          hello@contentgenie.app
        </a>
      </p>
    </article>
  );
}
